import type { Movie } from "./types.ts";

export const movies: Movie[] = [
    {
        id: 129,
        title: "The Shawshank Redemption",
        genre: ["Drama"],
        actors: "Tim Robbins, Morgan Freeman",
        duration: "02:22",
        releaseDate: new Date("1994-09-23"),
        isAvailable: true,
    },
    {
        id: 130,
        title: "The Matrix",
        genre: ["Action", "Sci-Fi"],
        actors: "Keanu Reeves, Laurence Fishburne",
        duration: "02:16",
        releaseDate: new Date("1999-03-31"),
        isAvailable: true,
    },
    {
        id: 131,
        title: "Inception",
        genre: ["Action", "Sci-Fi", "Thriller"],
        actors: "Leonardo DiCaprio, Joseph Gordon-Levitt",
        duration: "02:28",
        releaseDate: new Date("2010-07-16"),
        isAvailable: false,
    },
    {
        id: 132,
        title: "Inside Out",
        genre: ["Animation", "Family"],
        actors: "Amy Poehler, Phyllis Smith",
        duration: "01:35",
        releaseDate: new Date("2015-06-19"),
        isAvailable: true,
    },

    // weitere 10 Filme
    {
        id: 133,
        title: "The Dark Knight",
        genre: ["Action", "Crime", "Drama"],
        actors: "Christian Bale, Heath Ledger",
        duration: "02:32",
        releaseDate: new Date("2008-07-18"),
        isAvailable: true,
    },
    {
        id: 134,
        title: "Forrest Gump",
        genre: ["Drama", "Romance"],
        actors: "Tom Hanks, Robin Wright",
        duration: "02:22",
        releaseDate: new Date("1994-07-06"),
        isAvailable: true,
    },
    {
        id: 135,
        title: "Interstellar",
        genre: ["Adventure", "Drama", "Sci-Fi"],
        actors: "Matthew McConaughey, Anne Hathaway",
        duration: "02:49",
        releaseDate: new Date("2014-11-07"),
        isAvailable: false,
    },
    {
        id: 136,
        title: "Pulp Fiction",
        genre: ["Crime", "Drama"],
        actors: "John Travolta, Samuel L. Jackson",
        duration: "02:34",
        releaseDate: new Date("1994-10-14"),
        isAvailable: true,
    },
    {
        id: 137,
        title: "The Lion King",
        genre: ["Animation", "Adventure", "Drama"],
        actors: "Matthew Broderick, Jeremy Irons",
        duration: "01:28",
        releaseDate: new Date("1994-06-24"),
        isAvailable: true,
    },
    {
        id: 138,
        title: "Guardians of the Galaxy",
        genre: ["Action", "Adventure", "Sci-Fi"],
        actors: "Chris Pratt, Zoe Saldana",
        duration: "02:01",
        releaseDate: new Date("2014-08-01"),
        isAvailable: true,
    },
    {
        id: 139,
        title: "La La Land",
        genre: ["Comedy", "Drama", "Music"],
        actors: "Ryan Gosling, Emma Stone",
        duration: "02:08",
        releaseDate: new Date("2016-12-09"),
        isAvailable: false,
    },
    {
        id: 140,
        title: "Spirited Away",
        genre: ["Animation", "Adventure", "Family"],
        actors: "Rumi Hiiragi, Miyu Irino",
        duration: "02:05",
        releaseDate: new Date("2001-07-20"),
        isAvailable: true,
    },
    {
        id: 141,
        title: "The Godfather",
        genre: ["Crime", "Drama"],
        actors: "Marlon Brando, Al Pacino",
        duration: "02:55",
        releaseDate: new Date("1972-03-24"),
        isAvailable: true,
    },
    {
        id: 142,
        title: "Frozen",
        genre: ["Animation", "Adventure", "Comedy"],
        actors: "Kristen Bell, Idina Menzel",
        duration: "01:42",
        releaseDate: new Date("2013-11-27"),
        isAvailable: true,
    },
];
